<section class="jumbotron text-center dark-blue">
    <h1>KIV/WEB</h1>
    <h2>Semestrální práce</h2>
    <p>Webová konference</p>
</section>
<section class="jumbotron text-center blue">
    <h1><span class="glyphicon glyphicon-pencil">

        </span> Počet příspěvků</h1>
    <h1><?php echo $numPosts; ?></h1>
</section>
<section class="jumbotron text-center dark-blue">
    <h1><span class="glyphicon glyphicon-user">

        </span> Počet uživatelů</h1>
    <h1><?php echo $numUsers; ?></h1>
</section>
