
<section class="jumbotron dark-blue little-padding">
    <div class="container">
        <?php if (isset($error)) echo '<div class="alert alert-danger"><strong>Chyba!</strong> '.$error.'</div>'; ?>
        <?php if (isset($success)) echo '<div class="alert alert-success"><strong>Hotovo!</strong> '.$success.'</div>'; ?>
        <button type="button" class="btn btn-primary btn-lg back" onclick="back()"><span class="glyphicon glyphicon-chevron-left"></span> Zpět</button>
        <div class="row centered-form">
            <div class="box-middle sign-in" id="sign-in">
                <div class="container-fluid">
                    <form class="form-signin" data-toggle="validator" method="post" id="form-sign">
                        <h2 class="form-signin-heading">Registrace</h2>
                        <label for="email" class="sr-only">Email</label>
                        <input type="text" name="fullname" pattern=".{3,}" title="Minimálně 3 znaky" id="name" class="form-control" placeholder="Jméno"
                               value="<?php if (isset($_POST['fullname']) && isset($error)) echo(htmlspecialchars($_POST['fullname'])); ?>" required autofocus/>
                        <input type="email" name="email" id="email" class="form-control" placeholder="Emailová adresa"
                               value="<?php if (isset($_POST['email']) && isset($error)) echo(htmlspecialchars($_POST['email'])); ?>" required/>
                        <label for="password" class="sr-only">Heslo</label>
                        <input type="password" name="password"  pattern=".{6,}" title="Minimálně 6 znaků" id="password"
                               data-minlength="6" class="form-control" placeholder="Heslo" onkeyup="validatePassword(this.id,'password_verify')"
                               value="<?php if (isset($_POST['password']) && isset($error)) echo(htmlspecialchars($_POST['password'])); ?>" required />
                        <input type="password" name="password_verify"  onkeyup="validatePassword('password',this.id)" title="Minimálně 6 znaků" id="password_verify"
                               data-minlength="6" class="form-control" placeholder="Potvrzení hesla"
                               value="<?php if (isset($_POST['password_verify']) && isset($error)) echo(htmlspecialchars($_POST['password_verify'])); ?>" required>
                        <div class="radio inline-block">
                            <label><input type="radio" name="type" value="1" required>Muž</label>
                        </div>
                        <div class="radio inline-block">
                            <label><input type="radio" name="type" value="0">Žena</label>
                        </div>
                        <button class="button-my" type="submit" name="send_reg">Registrovat</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="jumbotron blue">
    <div class="container">
        <h1><span class="glyphicon glyphicon-pencil">

        </span> Registrace ...</h1>
    </div>
</section>